name: Build, Push Docker & Deploy to EC2

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/npm-hello-world:latest .

      - name: Docker images
        run: docker images

      - name: Push an Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/npm-hello-world:latest
          
      - name: Deploy to EC2 via SSH (Docker)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/hello-world || exit 1

            sudo fuser -k 3000/tcp || true
            
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ec2-user
            fi

            git config --global --add safe.directory /home/ec2-user/hello-world
            git pull origin main


            # Stop old container (prevents port 3000 conflict)
            sudo docker stop npm-app || true
            sudo docker rm npm-app || true

            # Pull latest image from DockerHub (IMPORTANT)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/npm-hello-world:latest

            # Run container
            sudo docker run -d \
              -p 3000:3000 \
              --name npm-app \
              ${{ secrets.DOCKER_USERNAME }}/npm-hello-world:latest
